In [31]:
import pandas as pd
import numpy as np

In [32]:
tr_df = pd.read_csv("0000000000002417_training_boston_x_y_train.csv")
tr_df.head(10)
tr_df.shape

(379, 14)

In [33]:
te = np.genfromtxt("0000000000002417_test_boston_x_test.csv", delimiter = ",")
te_df = pd.DataFrame(te, columns=tr_df.columns[0:tr_df.shape[1]-1])
te_df.shape

(127, 13)

In [34]:
te_df.head(10)
te_df[' Y'] = np.nan

In [35]:
df = pd.concat([tr_df, te_df], axis=0, ignore_index=True)
df

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007,22.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.408684,-0.487722,0.247057,-0.272599,-1.016689,-0.585014,-1.137046,0.336351,-0.523001,-0.060801,0.113032,0.431842,-0.498046,NaN
502,-0.408903,-0.487722,0.406098,-0.272599,-1.016689,-0.392685,-0.934351,0.811768,-0.637962,-0.708183,-1.135347,0.441052,-0.315820,NaN
503,-0.410014,2.087452,-1.378373,-0.272599,-1.241285,-0.570767,-1.780692,3.287300,-0.637962,0.016409,-0.071913,0.390945,-0.681674,NaN
504,-0.403176,-0.487722,-0.375976,-0.272599,-0.299707,-0.224575,0.591198,-0.795123,-0.523001,-0.143951,1.130230,0.340070,0.201421,NaN
505,-0.133563,-0.487722,1.231945,-0.272599,2.732346,-1.442658,0.904131,-0.978615,-0.523001,-0.031105,-1.736418,-2.938931,0.488777,NaN

In [36]:
from sklearn import preprocessing

In [37]:
df_y = df.values[:,13]
del df[' Y']
df_y

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32. , 26.2, 21.7, 20.6,
       20. ,  7.5, 33. , 14.9, 14.8, 50. , 26.4, 19.7, 15.6, 25. , 22.7,
       15.2, 37. , 31.6, 19.3, 15.6,  8.1, 23.7, 32. , 42.8, 21.4, 31.6,
       14.1, 27.5, 22.5, 13.6,  7.4, 18.8, 50. , 30.1, 10.4, 14.5, 41.7,
       14.6, 23.7, 16.1, 32.2, 14.2, 50. , 23. , 19.1, 15. , 15. , 18.5,
       10.4, 24.7, 36.5, 21.7, 48.3, 27.5, 12.6, 36.2, 29.9, 43.5, 19.6,
       19.4, 11.8, 34.9, 17.8, 14. , 16.2, 20. , 21.1, 16.6, 18.9, 14.5,
       19.3, 25. , 18.9, 31.1,  8.3, 17.9, 22.1, 19.5, 20.6, 20.9, 20.4,
       16.8, 12.1, 15.7, 32.9, 34.9, 14.3, 11.7, 30.1, 25. , 29.1, 33.1,
       36.2, 24.4, 22.9, 50. , 15.2, 46.7,  5.6, 13.8,  7.2, 27.1, 26.5,
       18.5, 22. , 21.9, 18.1, 16. , 17.5, 12.5, 28.7, 18.7, 23.1, 13.3,
       21. , 17. ,  8.4, 13.2, 22.8, 23.8, 20.4, 45.4, 19.2, 22.9,  9.5,
       20.1, 18.5, 19.4, 30.7, 18.5, 50. , 27.5, 33.2, 31.7, 18.4, 27.9,
       18.3, 20.2, 23.1,  8.4, 48.8, 13.8, 25.3, 31.2, 16.5, 18.8, 24.4,
       16.2, 13.4, 31.5, 23.7, 21.9, 25. , 20. , 26.6, 22.9, 19.9, 23.7,
       24.5, 37.6, 13.5, 19.5, 24.4, 34.6, 22.2, 24.7, 14.1, 33.2, 19.3,
       19.8, 50. , 13.1, 19. , 19.1, 36.4, 35.4, 23.5,  7.2, 15.3, 21.8,
       17.4, 22.6,  8.5, 24.8, 18.2, 21.7, 17.4, 50. , 27.1,  6.3, 24.2,
       24.3, 19.4, 17.4,  8.7, 17.8, 19.6, 43.1, 20.1, 10.8, 22. , 21.2,
       24.1, 28.7, 16.6,  7. , 22.7, 27. , 13.5, 16.1, 21.4, 24.6, 20.1,
       50. , 12.7, 23.1, 21.1, 13.3, 13.9, 21.7, 23.9, 20.3, 13.6, 20.8,
       50. , 14.3, 20.8, 22.6, 50. ,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])

In [38]:
x_scaled = preprocessing.scale(df.values[:,0:df.shape[1]])
scaled_df = pd.DataFrame(x_scaled, columns=df.columns[0:df.shape[1]])
scaled_df.head(5)

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007

In [39]:
df = scaled_df

In [40]:
df['CRIM_CRIM'] = df['# CRIM'] ** 2
df['ZN_ZN'] = df[' ZN'] ** 2
df['INDUS_INDUS'] = df[' INDUS'] ** 2
df['CHAS_CHAS'] = df[' CHAS'] ** 2
df['NOX_NOX'] = df[' NOX'] ** 2
df['RM_RM'] = df[' RM'] ** 2
df['AGE_AGE'] = df[' AGE'] ** 2
df['DIS_DIS'] = df[' DIS'] ** 2
df['RAD_RAD'] = df[' RAD'] ** 2
df['TAX_TAX'] = df[' TAX'] ** 2
df['PTRATIO_PTRATIO'] = df[' PTRATIO'] ** 2
df['B_B'] = df[' B'] ** 2
df['LSTAT_LSTAT'] = df[' LSTAT'] ** 2


df['CRIM_ZN'] = df['# CRIM'] * df[' ZN']
df['ZN_INDUS'] = df[' ZN'] * df[' INDUS']
df['INDUS_CHAS'] = df[' INDUS'] * df[' CHAS']
df['CHAS_NOX'] = df[' CHAS'] * df[' NOX']
df['NOX_RM'] = df[' NOX'] * df[' RM']
df['RM_AGE'] = df[' RM'] * df[' AGE']
df['AGE_DIS'] = df[' AGE'] * df[' DIS']
df['DIS_RAD'] = df[' DIS'] * df[' RAD']
df['RAD_TAX'] = df[' RAD'] * df[' TAX']
df['TAX_PTRATIO'] = df[' TAX'] * df[' PTRATIO']
df['PTRATIO_B'] = df[' PTRATIO'] * df[' B']
df['B_LSTAT'] = df[' B'] * df[' LSTAT']
df['LSTAT_CRIM'] = df[' LSTAT'] * df['# CRIM']
df

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,CHAS_NOX,NOX_RM,RM_AGE,AGE_DIS,DIS_RAD,RAD_TAX,TAX_PTRATIO,PTRATIO_B,B_LSTAT,LSTAT_CRIM
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,...,0.157053,-0.714391,1.041729,-0.437085,0.391718,0.962501,0.387462,-0.124442,-0.450803,0.447815
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,...,0.277148,-0.001978,-0.001631,-0.281975,-0.175912,0.031799,-0.006873,0.032911,-0.151546,0.212027
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,...,-0.372776,-0.601284,-0.302166,-0.396733,-0.959051,2.543244,1.234808,-3.061597,-3.382342,0.111544
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,...,-0.506999,-0.089121,-0.038382,-0.570986,-1.184196,2.543244,1.234808,-0.053274,-0.014230,0.006098
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,...,0.248890,0.350728,0.320670,-0.250858,-0.226259,0.721023,-0.019689,0.008863,0.012504,-0.011963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.408684,-0.487722,0.247057,-0.272599,-1.016689,-0.585014,-1.137046,0.336351,-0.523001,-0.060801,...,0.277148,0.594777,0.665188,-0.382446,-0.175912,0.031799,-0.006873,0.048812,-0.215077,0.203543
502,-0.408903,-0.487722,0.406098,-0.272599,-1.016689,-0.392685,-0.934351,0.811768,-0.637962,-0.708183,...,0.277148,0.399238,0.366905,-0.758475,-0.517877,0.451794,0.804033,-0.500747,-0.139293,0.129140
503,-0.410014,2.087452,-1.378373,-0.272599,-1.241285,-0.570767,-1.780692,3.287300,-0.637962,0.016409,...,0.338373,0.708485,1.016361,-5.853669,-2.097172,-0.010469,-0.001180,-0.028114,-0.266497,0.279496
504,-0.403176,-0.487722,-0.375976,-0.272599,-0.299707,-0.224575,0.591198,-0.795123,-0.523001,-0.143951,...,0.081700,0.067307,-0.132768,-0.470075,0.415850,0.075287,-0.162698,0.384357,0.068497,-0.081208
505,-0.133563,-0.487722,1.231945,-0.272599,2.732346,-1.442658,0.904131,-0.978615,-0.523001,-0.031105,...,-0.744834,-3.941843,-1.304352,-0.884796,0.511817,0.016268,0.054011,5.103212,-1.436482,-0.065283

In [41]:
df_ = pd.DataFrame(df_y, columns=tr_df.columns[tr_df.shape[1]-1:tr_df.shape[1]])
df = df.join(df_)
df.head(10)

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,NOX_RM,RM_AGE,AGE_DIS,DIS_RAD,RAD_TAX,TAX_PTRATIO,PTRATIO_B,B_LSTAT,LSTAT_CRIM,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,...,-0.714391,1.041729,-0.437085,0.391718,0.962501,0.387462,-0.124442,-0.450803,0.447815,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,...,-0.001978,-0.001631,-0.281975,-0.175912,0.031799,-0.006873,0.032911,-0.151546,0.212027,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,...,-0.601284,-0.302166,-0.396733,-0.959051,2.543244,1.234808,-3.061597,-3.382342,0.111544,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,...,-0.089121,-0.038382,-0.570986,-1.184196,2.543244,1.234808,-0.053274,-0.014230,0.006098,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,...,0.350728,0.320670,-0.250858,-0.226259,0.721023,-0.019689,0.008863,0.012504,-0.011963,22.5
5,-0.416934,1.014463,-1.403178,-0.272599,-0.973497,1.362495,-0.685427,1.541554,-0.982843,-0.737880,...,-1.326385,-0.933890,-1.056622,-1.515106,0.725220,1.008333,-0.570346,-0.419069,0.418633,32.7
6,-0.002920,-0.487722,1.015999,-0.272599,0.218592,0.217069,0.228480,-0.427139,1.661245,1.530926,...,0.047450,0.049596,-0.097593,-0.709583,2.543244,1.234808,0.324524,0.096269,-0.000699,23.2
7,-0.225559,-0.487722,1.231945,-0.272599,2.732346,-0.231698,1.021481,-1.034899,-0.523001,-0.031105,...,-0.633081,-0.236676,-1.057130,0.541254,0.016268,0.054011,-0.307018,0.035861,-0.045748,21.5
8,-0.395561,0.456508,-0.769931,-0.272599,-1.068519,-0.083534,0.377835,2.025290,-0.293081,-0.464673,...,0.089258,-0.031562,0.765225,-0.593573,0.136187,-0.138462,0.063598,-0.074886,0.138788,20.5
9,-0.413779,2.945843,-1.403178,-0.272599,-1.301754,1.428029,-1.225947,1.670427,-0.867882,-0.470612,...,-1.858942,-1.750688,-2.047855,-1.449734,0.408436,1.274125,-1.194095,-0.530020,0.497246,33.3

In [46]:
tr_df = df[0:379]
te_df = df[379:506]
del te_df[' Y']
te_df = te_df.reset_index(drop=True)

In [47]:
train_data = tr_df.values
test_data = te_df.values

In [49]:
np.savetxt("new_training_boston_x_y_train.csv", train_data, delimiter=',')
np.savetxt("new_test_boston_x_test.csv", test_data, delimiter=',')

In [50]:
train_data = np.genfromtxt("new_training_boston_x_y_train.csv", delimiter = ",")

In [51]:
def step_grad(points, learn_rate, M):
    N = points.shape[0]
    num_col = points.shape[1]
    
    new_M = np.zeros(num_col)
    
    for i in range(N):
        x = points[i, 0:num_col-1]
        x = np.append(x, 1)
        y = points[i, num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N) * (y - (M * x).sum()) * x[j]
        M = M - (learn_rate * new_M)
    
    return M

In [52]:
def grad_desc(points, learn_rate, num_iter):
    num_col = points.shape[1]
    M = np.zeros(num_col)
    
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)
        if i % 100== 0:
            print(i, "Cost= ", cost(points, M))
    print(i, "Cost= ", cost(points, M))
    return M

In [53]:
def cost(points, M):
    total_cost = 0
    
    N = points.shape[0]
    num_col = points.shape[1]
    
    for i in range(N):
        x = points[i,0:num_col-1]
        x = np.append(x, 1)
        y = points[i,num_col-1]
        total_cost += (y - (M * x).sum()) ** 2
        
    total_cost = (1/N) * total_cost
    return total_cost

In [54]:
def run():
    data = train_data[:,0:train_data.shape[1]]
    # tweak learn_rate & num_iter to get better results; 0.001, 1000
    learn_rate = 0.0001
    num_iter = 1000
    
    m = grad_desc(data, learn_rate, num_iter)
    #print(m)
    return m[0:train_data.shape[1]-1], m[train_data.shape[1]-1]

In [55]:
m, c = run()
print(m, c)

0 Cost=  232.85429729699655
100 Cost=  26.117435513235414
200 Cost=  20.807970997862018
300 Cost=  18.491477684566856
400 Cost=  17.295590503908187
500 Cost=  16.588364912869846
600 Cost=  16.124640628507375
700 Cost=  15.797988169656081
800 Cost=  15.55676381804588
900 Cost=  15.373037843593497
999 Cost=  15.231438736989691
[-2.79910816 -2.14223279 -0.64122725 -3.90491246 -3.82440048  2.07010127
 -0.26329036 -3.82225412  1.62304567 -1.13737351 -0.7594548   0.11187316
 -4.85803434  0.2026936   0.35111883  1.03525071  1.42768592  0.60066423
  0.78147264  0.64096936  1.27252904  0.06741108 -0.57506292  0.6967832
 -0.25750352  0.69062557 -0.62864675  0.15468724  1.84684314 -1.1877101
 -0.41597022 -0.86382797  1.45231418 -0.10892044  1.15812979  1.13591977
  0.19710044 -0.56135944 -0.42226331] 14.687984890833274

In [56]:
test_data = np.genfromtxt("new_test_boston_x_test.csv", delimiter = ",")

In [57]:
def predict(x, m, c):
    N = x.shape[0]
    y = np.zeros(N)
    
    for i in range(N):
        X = x[i,:]
        y[i] = (m * X).sum() + c
        
    return y

In [60]:
y_pred = predict(test_data, m, c)
y_pred.mean()
tr_df[' Y'].mean()

22.609498680738778

In [62]:
np.savetxt("assignment1.csv", y_pred, delimiter=',',fmt="%f")