In [137]:
import pandas as pd
import numpy as np

In [138]:
tr_df = pd.read_csv("0000000000002417_training_boston_x_y_train.csv")
tr_df.head(10)
tr_df.shape

(379, 14)

In [139]:
te = np.genfromtxt("0000000000002417_test_boston_x_test.csv", delimiter = ",")
te_df = pd.DataFrame(te, columns=tr_df.columns[0:tr_df.shape[1]-1])
te_df.shape

(127, 13)

In [140]:
te_df.head(10)
te_df[' Y'] = np.nan

In [141]:
df = pd.concat([tr_df, te_df], axis=0, ignore_index=True)
df.describe()

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
count,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,379.000000
mean,-3.952570e-11,3.458498e-09,-1.976285e-10,-2.707510e-09,1.383399e-10,2.173913e-10,4.347826e-10,-1.976285e-11,-1.837945e-09,4.206533e-17,-1.719368e-09,-5.928854e-10,1.778656e-10,22.609499
std,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,9.389647
min,-4.177133e-01,-4.877224e-01,-1.557842e+00,-2.725986e-01,-1.465882e+00,-3.880249e+00,-2.335437e+00,-1.267069e+00,-9.828429e-01,-1.313990e+00,-2.707379e+00,-3.907193e+00,-1.531127e+00,5.000000
25%,-4.088961e-01,-4.877224e-01,-8.676906e-01,-2.725986e-01,-9.130288e-01,-5.686303e-01,-8.374480e-01,-8.056878e-01,-6.379618e-01,-7.675760e-01,-4.880391e-01,2.050715e-01,-7.994200e-01,16.700000
50%,-3.885818e-01,-4.877224e-01,-2.110985e-01,-2.725986e-01,-1.442174e-01,-1.084655e-01,3.173816e-01,-2.793234e-01,-5.230014e-01,-4.646726e-01,2.748590e-01,3.811865e-01,-1.812536e-01,21.100000
75%,6.248253e-03,4.877224e-02,1.015999e+00,-2.725986e-01,5.986790e-01,4.827678e-01,9.067981e-01,6.623710e-01,1.661245e+00,1.530926e+00,8.065758e-01,4.336510e-01,6.030187e-01,25.750000
max,9.941735e+00,3.804234e+00,2.422565e+00,3.668398e+00,2.732346e+00,3.555044e+00,1.117494e+00,3.960518e+00,1.661245e+00,1.798194e+00,1.638828e+00,4.410519e-01,3.548771e+00,50.000000

In [142]:
df_y = df.values[:,13]
del df[' Y']
df_y

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32. , 26.2, 21.7, 20.6,
       20. ,  7.5, 33. , 14.9, 14.8, 50. , 26.4, 19.7, 15.6, 25. , 22.7,
       15.2, 37. , 31.6, 19.3, 15.6,  8.1, 23.7, 32. , 42.8, 21.4, 31.6,
       14.1, 27.5, 22.5, 13.6,  7.4, 18.8, 50. , 30.1, 10.4, 14.5, 41.7,
       14.6, 23.7, 16.1, 32.2, 14.2, 50. , 23. , 19.1, 15. , 15. , 18.5,
       10.4, 24.7, 36.5, 21.7, 48.3, 27.5, 12.6, 36.2, 29.9, 43.5, 19.6,
       19.4, 11.8, 34.9, 17.8, 14. , 16.2, 20. , 21.1, 16.6, 18.9, 14.5,
       19.3, 25. , 18.9, 31.1,  8.3, 17.9, 22.1, 19.5, 20.6, 20.9, 20.4,
       16.8, 12.1, 15.7, 32.9, 34.9, 14.3, 11.7, 30.1, 25. , 29.1, 33.1,
       36.2, 24.4, 22.9, 50. , 15.2, 46.7,  5.6, 13.8,  7.2, 27.1, 26.5,
       18.5, 22. , 21.9, 18.1, 16. , 17.5, 12.5, 28.7, 18.7, 23.1, 13.3,
       21. , 17. ,  8.4, 13.2, 22.8, 23.8, 20.4, 45.4, 19.2, 22.9,  9.5,
       20.1, 18.5, 19.4, 30.7, 18.5, 50. , 27.5, 33.2, 31.7, 18.4, 27.9,
       18.3, 20.2, 23.1,  8.4, 48.8, 13.8, 25.3, 31.2, 16.5, 18.8, 24.4,
       16.2, 13.4, 31.5, 23.7, 21.9, 25. , 20. , 26.6, 22.9, 19.9, 23.7,
       24.5, 37.6, 13.5, 19.5, 24.4, 34.6, 22.2, 24.7, 14.1, 33.2, 19.3,
       19.8, 50. , 13.1, 19. , 19.1, 36.4, 35.4, 23.5,  7.2, 15.3, 21.8,
       17.4, 22.6,  8.5, 24.8, 18.2, 21.7, 17.4, 50. , 27.1,  6.3, 24.2,
       24.3, 19.4, 17.4,  8.7, 17.8, 19.6, 43.1, 20.1, 10.8, 22. , 21.2,
       24.1, 28.7, 16.6,  7. , 22.7, 27. , 13.5, 16.1, 21.4, 24.6, 20.1,
       50. , 12.7, 23.1, 21.1, 13.3, 13.9, 21.7, 23.9, 20.3, 13.6, 20.8,
       50. , 14.3, 20.8, 22.6, 50. ,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])

In [143]:
df['CRIM_CRIM'] = df['# CRIM'] ** 2
df['ZN_ZN'] = df[' ZN'] ** 2
df['INDUS_INDUS'] = df[' INDUS'] ** 2
df['CHAS_CHAS'] = df[' CHAS'] ** 2
df['NOX_NOX'] = df[' NOX'] ** 2
df['RM_RM'] = df[' RM'] ** 2
df['AGE_AGE'] = df[' AGE'] ** 2
df['DIS_DIS'] = df[' DIS'] ** 2
df['RAD_RAD'] = df[' RAD'] ** 2
df['TAX_TAX'] = df[' TAX'] ** 2
df['PTRATIO_PTRATIO'] = df[' PTRATIO'] ** 2
df['B_B'] = df[' B'] ** 2
df['LSTAT_LSTAT'] = df[' LSTAT'] ** 2

df

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,CHAS_CHAS,NOX_NOX,RM_RM,AGE_AGE,DIS_DIS,RAD_RAD,TAX_TAX,PTRATIO_PTRATIO,B_B,LSTAT_LSTAT
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,...,0.07431,0.331930,1.537535,0.705805,0.270675,0.566892,1.634190,0.091866,0.168569,1.205582
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,...,0.07431,1.033656,0.000004,0.702809,0.113132,0.273531,0.003697,0.012776,0.084779,0.270893
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,...,0.07431,1.870030,0.193335,0.472260,0.333285,2.759736,2.343736,0.650565,14.408063,0.794016
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,...,0.07431,3.459136,0.002296,0.641610,0.508136,2.759736,2.343736,0.650565,0.004363,0.046414
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,...,0.07431,0.833622,0.147561,0.696859,0.090305,0.566892,0.917061,0.000423,0.185825,0.000841
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.408684,-0.487722,0.247057,-0.272599,-1.016689,-0.585014,-1.137046,0.336351,-0.523001,-0.060801,...,0.07431,1.033656,0.342241,1.292873,0.113132,0.273531,0.003697,0.012776,0.186487,0.248050
502,-0.408903,-0.487722,0.406098,-0.272599,-1.016689,-0.392685,-0.934351,0.811768,-0.637962,-0.708183,...,0.07431,1.033656,0.154201,0.873011,0.658967,0.406995,0.501523,1.289012,0.194527,0.099743
503,-0.410014,2.087452,-1.378373,-0.272599,-1.241285,-0.570767,-1.780692,3.287300,-0.637962,0.016409,...,0.07431,1.540789,0.325775,3.170864,10.806341,0.406995,0.000269,0.005171,0.152838,0.464679
504,-0.403176,-0.487722,-0.375976,-0.272599,-0.299707,-0.224575,0.591198,-0.795123,-0.523001,-0.143951,...,0.07431,0.089825,0.050434,0.349515,0.632220,0.273531,0.020722,1.277419,0.115648,0.040570
505,-0.133563,-0.487722,1.231945,-0.272599,2.732346,-1.442658,0.904131,-0.978615,-0.523001,-0.031105,...,0.07431,7.465717,2.081263,0.817453,0.957688,0.273531,0.000968,3.015147,8.637314,0.238903

In [144]:
from sklearn import preprocessing

In [145]:
x_scaled=preprocessing.scale(df.values[:,:])
scaled_df = pd.DataFrame(x_scaled, columns=df.columns[0:df.shape[1]])
scaled_df.describe()

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,CHAS_CHAS,NOX_NOX,RM_RM,AGE_AGE,DIS_DIS,RAD_RAD,TAX_TAX,PTRATIO_PTRATIO,B_B,LSTAT_LSTAT
count,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,...,5.060000e+02,506.000000,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02
mean,4.914821e-17,-1.029041e-16,3.247293e-17,-2.826022e-16,4.388233e-18,4.388233e-18,-7.657467e-17,-8.776467e-19,3.861645e-17,-8.518658e-17,...,-2.393781e-16,0.000000,-4.607645e-17,3.291175e-19,-4.391662e-17,-1.347188e-16,-6.362938e-17,8.820349e-17,3.598351e-17,-2.874293e-17
std,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,...,1.000990e+00,1.000990,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00
min,-4.177133e-01,-4.877224e-01,-1.557842e+00,-2.725986e-01,-1.465882e+00,-3.880249e+00,-2.335437e+00,-1.267069e+00,-9.828429e-01,-1.313990e+00,...,-2.725986e-01,-0.719726,-5.089170e-01,-9.853164e-01,-6.361173e-01,-9.110846e-01,-1.079913e+00,-7.653176e-01,-3.306984e-01,-6.354413e-01
25%,-4.088961e-01,-4.877224e-01,-8.676906e-01,-2.725986e-01,-9.130288e-01,-5.686303e-01,-8.374480e-01,-8.056878e-01,-6.379618e-01,-7.675760e-01,...,-2.725986e-01,-0.613448,-4.787795e-01,-7.091743e-01,-5.188545e-01,-6.835625e-01,-8.409652e-01,-6.749259e-01,-2.947763e-01,-5.569995e-01
50%,-3.885818e-01,-4.877224e-01,-2.110985e-01,-2.725986e-01,-1.442174e-01,-1.084655e-01,3.173816e-01,-2.793234e-01,-5.230014e-01,-4.646726e-01,...,-2.725986e-01,-0.262568,-3.659780e-01,-1.893430e-01,-2.584681e-01,-5.579805e-01,-4.239266e-01,-2.675422e-01,-2.752092e-01,-3.103007e-01
75%,6.248253e-03,4.877224e-02,1.015999e+00,-2.725986e-01,5.986789e-01,4.827678e-01,9.067981e-01,6.623709e-01,1.661245e+00,1.530926e+00,...,-2.725986e-01,0.308092,-2.828896e-02,2.451456e-01,7.192363e-02,1.655802e+00,1.451509e+00,2.212795e-01,-2.663719e-01,1.262414e-01
max,9.941735e+00,3.804234e+00,2.422565e+00,3.668398e+00,2.732346e+00,3.555044e+00,1.117494e+00,3.960518e+00,1.661245e+00,1.798194e+00,...,3.668398e+00,4.661212,7.153535e+00,4.388949e+00,9.341832e+00,1.655802e+00,2.412638e+00,4.846434e+00,4.717853e+00,7.367188e+00

In [146]:
df=scaled_df

In [147]:
df_ = pd.DataFrame(df_y, columns=tr_df.columns[tr_df.shape[1]-1:tr_df.shape[1]])
df = df.join(df_)
df.head(10)

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,NOX_NOX,RM_RM,AGE_AGE,DIS_DIS,RAD_RAD,TAX_TAX,PTRATIO_PTRATIO,B_B,LSTAT_LSTAT,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,...,-0.481619,0.273562,-0.289881,-0.463936,-0.407528,0.685054,-0.695305,-0.274956,0.130636,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,...,0.024263,-0.508917,-0.292833,-0.564152,-0.683562,-1.076211,-0.755859,-0.302666,-0.463306,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,...,0.627215,-0.410527,-0.520001,-0.424109,1.655802,1.451509,-0.267542,4.434079,-0.130891,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,...,1.772820,-0.507750,-0.353135,-0.312884,1.655802,1.451509,-0.267542,-0.329260,-0.605950,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,...,-0.119944,-0.433822,-0.298696,-0.578673,-0.407528,-0.089591,-0.765318,-0.269250,-0.634909,22.5
5,-0.416934,1.014463,-1.403178,-0.272599,-0.973497,1.362495,-0.685427,1.541554,-0.982843,-0.737880,...,-0.037706,0.435834,-0.522416,0.875546,-0.032011,-0.492069,0.664116,-0.273095,0.005188,32.7
6,-0.002920,-0.487722,1.015999,-0.272599,0.218592,0.217069,0.228480,-0.427139,1.661245,1.530926,...,-0.686465,-0.484939,-0.933898,-0.520059,1.655802,1.451509,-0.267542,-0.277167,-0.599065,23.2
7,-0.225559,-0.487722,1.231945,-0.272599,2.732346,-0.231698,1.021481,-1.034899,-0.523001,-0.031105,...,4.661212,-0.481598,0.042787,0.045174,-0.683562,-1.079159,1.542880,-0.320364,-0.609303,21.5
8,-0.395561,0.456508,-0.769931,-0.272599,-1.068519,-0.083534,0.377835,2.025290,-0.293081,-0.464673,...,0.102177,-0.505368,-0.844670,1.973109,-0.860115,-0.846966,-0.697660,-0.315638,-0.557217,20.5
9,-0.413779,2.945843,-1.403178,-0.272599,-1.301754,1.428029,-1.225947,1.670427,-0.867882,-0.470612,...,0.500718,0.528902,0.495571,1.138858,-0.232205,-0.840965,4.846434,-0.266372,0.282218,33.3

In [148]:
tr_df = df[0:379]
te_df = df[379:506]
del te_df[' Y']
te_df = te_df.reset_index(drop=True)

In [149]:
train_data = tr_df.values
test_data = te_df.values

In [150]:
np.savetxt("new_training_boston_x_y_train.csv", train_data, delimiter=',')
np.savetxt("new_test_boston_x_test.csv", test_data, delimiter=',')

In [151]:
train_data = np.genfromtxt("new_training_boston_x_y_train.csv", delimiter = ",")

In [152]:
def step_grad(points, learn_rate, M):
    N = points.shape[0]
    num_col = points.shape[1]
    
    new_M = np.zeros(num_col)
    
    for i in range(N):
        x = points[i, 0:num_col-1]
        x = np.append(x, 1)
        y = points[i, num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N) * (y - (M * x).sum()) * x[j]
        M = M - (learn_rate * new_M)
    
    return M

In [153]:
def grad_desc(points, learn_rate, num_iter):
    num_col = points.shape[1]
    M = np.zeros(num_col)
    
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)
        if i % 100== 0:
            print(i, "Cost= ", cost(points, M))
    print(i, "Cost= ", cost(points, M))
    return M

In [154]:
def cost(points, M):
    total_cost = 0
    
    N = points.shape[0]
    num_col = points.shape[1]
    
    for i in range(N):
        x = points[i,0:num_col-1]
        x = np.append(x, 1)
        y = points[i,num_col-1]
        total_cost += (y - (M * x).sum()) ** 2
        
    total_cost = (1/N) * total_cost
    return total_cost

In [155]:
def run():
    data = train_data[:,0:train_data.shape[1]]
    # tweak learn_rate & num_iter to get better results; 0.001, 1000
    learn_rate = 0.0001
    num_iter = 1000
    
    m = grad_desc(data, learn_rate, num_iter)
    #print(m)
    return m[0:train_data.shape[1]-1], m[train_data.shape[1]-1]

In [157]:
m, c = run()
print(m, c)

0 Cost=  544.1993430449353
100 Cost=  20.522016781154395
200 Cost=  18.589371086562306
300 Cost=  17.888778276537668
400 Cost=  17.511894183368728
500 Cost=  17.282593042413726
600 Cost=  17.13137630516065
700 Cost=  17.026134501484986
800 Cost=  16.950161879772725
900 Cost=  16.893892237362863
999 Cost=  16.851797463473535
[-2.18726413 -0.64944455 -0.67272876  0.40174756 -2.44480732  1.90537639
 -0.16932354 -2.89211316  2.49848305 -1.4552711  -1.35615152 -0.54115256
 -4.79490117  0.82817026  0.33756284  0.57464512  0.40174756  0.15248923
  1.91835589  0.01644416  0.7761332   0.16310052  0.10182391  0.40992688
 -1.11153047  1.34208066] 22.617435930267746

In [158]:
test_data = np.genfromtxt("new_test_boston_x_test.csv", delimiter = ",")

In [159]:
def predict(x, m, c):
    N = x.shape[0]
    y = np.zeros(N)
    
    for i in range(N):
        X = x[i,:]
        y[i] = (m * X).sum() + c
    return y

In [160]:
y_pred = predict(test_data, m, c)
print(y_pred.mean())
print(tr_df[' Y'].mean())

22.706060513681727
22.609498680738778

In [161]:
np.savetxt("assignment1.csv", y_pred, delimiter=',',fmt="%f")